-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 22:34:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfirst` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbfirst` ;

-- -----------------------------------------------------
-- Table `dbfirst`.`afgelast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`afgelast` (
  `Plaats` INT NOT NULL,
  `tijd` VARCHAR(45) NULL DEFAULT NULL,
  `team` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Plaats`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbfirst`.`thuis wedstrijd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`thuis wedstrijd` (
  `Plaats` INT NOT NULL,
  `Tijd` VARCHAR(45) NULL DEFAULT NULL,
  `team` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Plaats`),
  UNIQUE INDEX `Plaats_UNIQUE` (`Plaats` ASC) VISIBLE,
  UNIQUE INDEX `team_UNIQUE` (`team` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbfirst`.`uit wedstrijd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`uit wedstrijd` (
  `plaats` INT NOT NULL,
  `tijd` VARCHAR(45) NULL DEFAULT NULL,
  `team` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`plaats`),
  UNIQUE INDEX `team_UNIQUE` (`team` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
